[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor
monitor_speed = 115200

; Memory Configuration for N16R8 (16MB Flash, 8MB PSRAM)
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1

; Automatically download the required I2C LCD library
lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4